replicaCount: 1

image:
  repository: todoclusterregistry.azurecr.io/todo_app
  tag: "16893493622"
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
