apiVersion: v1
kind: Service
metadata:
  name: todo_app
  labels:
    app: todo_app
spec:
  selector:
    app: todo_app
  type: clusterIP
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
