name: CI 

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flake8
          # Uncomment if you have requirements.txt:
          # pip install -r requirements.txt

      - name: Run flake8 linting
        run: flake8 .

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: todoclusterregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: todoclusterregistry.azurecr.io/todo_app:${{ github.run_id }}

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update image tag in Helm chart
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" helm/todo-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "Sasinda Prabhath"
          git config --global user.email "sasindaprabhath94@gmail.com"
          git add helm/todo-app-chart/values.yaml
          git commit -m "Update image tag to ${{ github.run_id }}"
          git push
